version: "3.8"

services:
  aroundtec-db:
    build: ./BD
    image: aroundtec-db
    container_name: aroundtec-db
    ports:
      - "9000:3306"
    volumes:
      - aroundtec-db-data:/var/lib/mysql
    networks:
      - aroundtec-net

  aroundtec-front:
    build: ./FRONT
    image: aroundtec-front
    container_name: aroundtec-front
    depends_on:
      - aroundtec-db
    ports:
      - "3000:3000"
    networks:
      - aroundtec-net
  
  aroundtec-back:
    build: ./BACK
    image: aroundtec-back
    container_name: aroundtec-back
    depends_on:
      - aroundtec-front
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://aroundtec-db/aroundtech-v2
    networks:
      - aroundtec-net
    restart: on-failure

  aroundtec-abs:
    build: ./ABSENCES
    image: aroundtec-abs
    container_name: aroundtec-abs
    depends_on:
      - aroundtec-front
    ports:
      - "8082:8082"
    networks:
      - absence-net

networks:
  aroundtec-net:
  absence-net:
volumes:
  aroundtec-db-data:
